INJIMOB-2023 fixed inji-wallet ui automation for Ios and android
mosip/inji-wallet pull request #1618
Opened 2024-09-18 04:00 UTC by anup-nehe

INJIMOB-2023 fixed inji-wallet ui automation for Ios and android

2024-09-18 05:17 UTC, swatigoel approved these changes

2024-09-18 05:47 UTC, sree96 commented on injitest/iosRegression.xml
> -<!--                    <include name="downloadMultipleVcViaEsignet"/>  invalid testcase -->
Remove unused code Please

2024-09-18 05:48 UTC, sree96 commented on injitest/src/test/java/iosTestCases/VerifyWelcomePagesTest.java
> +//        assertTrue(esignetLoginPage.isEnterYourVidTextDisplayed(), "Verify if enter your vid text is displayed");
Remove unused code Please

2024-09-18 05:49 UTC, sree96 commented on injitest/src/test/java/iosTestCases/VerifyWelcomePagesTest.java
> +//        assertTrue(esignetLoginPage.isEnterYourVidTextDisplayed(), "Verify if enter your vid text is displayed");
Remove unused code Please

2024-09-18 05:49 UTC, sree96 commented on injitest/src/test/java/iosTestCases/VerifyWelcomePagesTest.java
> +//        assertTrue(esignetLoginPage.isOtpHasSendMessageDisplayed(),"verify if otp page is displayed");
Remove unused code Please

2024-09-18 05:49 UTC, sree96 requested changes
Please address the comments

2024-09-20 05:09 UTC, sree96 approved these changes

2024-09-20 05:09 UTC, merged