[INJIMOB-2415] show credential type in mini view instead of fullName
mosip/inji-wallet pull request #1705
Opened 2024-11-26 03:16 UTC by KiruthikaJeyashankar

## Description

> Dispaly credential type in mini view instead of fullName

Previously, it was showing hardcoded fullName in mini view, which is now replaced with showing the credential type as per configured issuer metadata

## Issue ticket number and link

> [INJIMOB-2415](https://mosip.atlassian.net/browse/INJIMOB-2415&#41)

## Screenshots

1. Issuer metadata exposes credential type 
![image](https://github.com/user-attachments/assets/afef279d-8f67-423f-9b90-5b43658d0aa0)

2. Issuer metadata does not expose credential type so show fallback
![image](https://github.com/user-attachments/assets/01763448-016a-43e1-8da9-d4119fda6aed)

2024-11-26 08:41 UTC, swatigoel requested changes

2024-11-28 03:06 UTC, KiruthikaJeyashankar commented on components/VC/common/VCUtils.tsx
> +  const defaultCredentialType = i18n.t('VcDetails:nationalCard');
Given only ldp_vcs have credential_definition.type, can we populate fallback credential type as per VC formats?

2024-11-28 03:12 UTC, KiruthikaJeyashankar commented on components/VC/common/VCUtils.tsx
> +export const getCredentialType = (
**On #2** As per draft 13 open4vci spec, 
`name: OPTIONAL. String value of a display name for the Credential Issuer.`
Ref- https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#name-oauth-20-authorization-serv
Given this is the case, are we mandating name for this wallet app?

**On #3** Given only ldp_vcs have credential_definition.type, can we populate fallback credential type as per VC formats?

**On #4** locale filtering is happening where fallback is set to first element of display array, will change it to accept english locale

2024-11-28 05:05 UTC, KiruthikaJeyashankar commented on components/VC/common/VCUtils.tsx
> +  const defaultCredentialType = i18n.t('VcDetails:nationalCard');
**Refactor to be made** as per discussion
1. name is mandatory in display of credential_configurations_supported
2. accept only whole wellknown as inputparam for function
3. display? get name : credential_definition.type // get language specifics before getting any data from display

2024-11-28 06:30 UTC, KiruthikaJeyashankar commented on components/VC/common/VCUtils.tsx
> + * supportedCredential's wellknown is passed from getActivityText after fresh download and viewing of card's mini view flow
Can we update this comment with caller flows - mini view & detail view or remove this point?

2024-11-28 06:31 UTC, KiruthikaJeyashankar commented on components/VC/common/VCUtils.tsx
> +    return i18n.t('VcDetails:nationalCard');
fallback scenario for mso_mdoc = "Identity Card"
https://github.com/mosip/inji-wallet/pull/1705#discussion_r1861512414

2024-11-28 09:34 UTC, swatigoel requested changes

2024-11-28 09:34 UTC, swatigoel commented on components/VC/common/VCUtils.tsx
> +        ? wellknown.display[0]?.background_color
we don't have to pick 0th element. It has to be filtered based on locale

2024-11-28 09:34 UTC, swatigoel commented on components/VC/common/VCUtils.tsx
> +      ? wellknown.display[0]?.background_image
we don't have to pick 0th element. It has to be filtered based on locale

2024-11-28 09:34 UTC, swatigoel commented on components/VC/common/VCUtils.tsx
> +    (wellknown?.display?.length ? wellknown.display[0]?.text_color : null) ??
we don't have to pick 0th element. It has to be filtered based on locale

2024-11-28 09:34 UTC, swatigoel commented on components/VC/common/VCUtils.tsx
> +    }
why this commented code?

2024-11-28 09:34 UTC, swatigoel commented on components/VC/common/VCUtils.tsx
> +      throw new Error(`Invalid credentialConfigurationId - ${credentialConfigurationId} passed`);
why this commented code

2024-11-29 12:00 UTC, swatigoel approved these changes

2024-11-29 12:00 UTC, merged